### ISSUE TITLE
Readme add "(POS)" near "POint Of Sale" title

### ISSUE THREAD

**Issue by Master0229** [BizDom/Biz1Book#1]
alksjlkasjdlkasjdlkjsaldkjsa
![image](https://github.com/BizDom/Biz1Book/assets/73741269/6b949863-4538-4944-bfa2-9ca89338b555)

**Comment by mohamed1408** [comment]
In Progress 50% completed

**Comment by Master0229** [comment]
Ok Make iit fast

**Comment by mohamed1408** [comment]
Stuck on an issue

**Comment by mohamed1408** [comment]
pull request created

**Comment by Master0229** [comment]
closed
